### ISSUE TITLE
Is this the latest Docs with EVERYTHING I need to know?

### ISSUE THREAD

**Issue by FrozenBeard** [Hazebyte/Documentation#7]
Your documentation is all over the place, website docs are not finished, no idea if there updated, spigot is lacking and I found this too? Which one is the latest and has everything documented?

**Comment by imWillX** [comment]
Hey @FrozenBeard 

Thanks for pointing this out. I noticed and i'm working on it. The documentation for the latest version is located [here](https://crate.hazebyte.com/guide/pro/user/start-guide/).

This page is a WIP documentation for CrateReloaded 2.0.0. Once the plugin version and documentation is finished, we will update the main website, crate.hazebyte.com with the latest information. 

Regards,
Will
